config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get "search" => "games#search"

  resources :users do
    resources :requests
  end

  resources :games do
    resources :reviews do
      member do
        post 'toggle_good'
      end
    end
    resources :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :requests do
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :games
  has_many :favorites
  has_many :favorite_games, through: :favorites, source: :game
  has_many :reviews, dependent: :destroy
  has_many :requests, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: { maximum: 50}

  def favorited?(game)
    favorite_games.exists?(id: game.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @game = Game.find(params[:id])
    @latest_review = @user.reviews.last
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @games = @user.games
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user), notice: "ユーザー情報を編集しました！"
    else
     render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.erb
<div class="card user-info p-3">
  <% if @user.id == current_user.id %>
    <div class="user-info-update ml-auto">
      <%= link_to edit_user_path(@user), class: 'btn btn-outline-dark rounded-pill btn-sm font-jp' do %>
        編集 <i class="fa-regular fa-pen-to-square"></i>
      <% end %>
    </div>
  <% end %>

  <div class="container-fluid">
    <div class="row user-date mt-1 mb-1">
      <div class="col-6 col-md-12 d-flex justify-content-center pb-2">
        <div class="user-date-img">
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "user.png", size: '100x100' %>
        </div>
      </div>
      <div class="col-6 col-md-12 d-flex align-items-center justify-content-center">
        <p class="font-jp"><strong><%= @user.name %></strong></p>
      </div>
    </div>
    <div class="row user-intro">
      <%if @user.introduction.nil? %>
        <p class="font-jp"><%=@user.introduction%></p>
      <% else %>
        <p class="font-jp"><%=safe_join(@user.introduction.split("\n"),tag(:br))%></p>
      <%end %>
    </div>
</div>
</div>

app/views/users/edit.html.erb
<main>
  <% if flash[:notice] %>
    <div class="alert alert-success font-jp">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <section class="user-edit section-back mt-3">
          <h2 class="font-jp">プロフィール編集</h2>
          <% if @user.errors.any? %>
            <h3>
            <%= @user.errors.count %>errors prohibited this obj from being saved:
            </h3>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          <% end %>
          <%= form_with model: @user, local:true do |f| %>
            <div class="custom-file mb-3">
              <input type="file" class="custom-file-input" id="customFile">
              <label class="custom-file-label" for="customFile" data-browse="選択">画像を選択...</label>
            </div>
            <div class="form-group">
              <label for="user_name">ユーザー名</label>
              <%= f.text_field :name, autofocus: true, class: 'form-control'%>
            </div>
            <div class="form-group">
              <label for="user_Introduction">自己紹介</label>
              <%= f.text_area :introduction, autofocus: true, class: 'form-control'%>
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-block btn-dark">変更内容を保存</button>
            </div>
          <% end %>
        </section>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <% if flash[:notice] %>
    <div class="alert alert-success font-jp">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="container px-5 px-sm-0">
    <h1 class="heading-custom" data-en="All Users">ユーザー一覧</h1>
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/userinfo', user: @user %>
      </div>
      <div class="col-md-9">
        <section class="all-users section-back mt-3">
        <h3 class="font-al">Users</h3>
        <table class="table text-center font-jp">
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "user.png", size: '50x50' %></td>
              <td class="align-middle"><%= link_to user.name, user_path(user) %></td>
              <td class="align-middle"><%= link_to user.reviews.count, user_path(user) %> 件の課金レビュー</td>
              <td class="align-middle"><%= link_to '詳細', user_path(user.id), class: 'btn btn-outline-secondary' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0 mt-3">
    <% if flash[:notice] %>
      <div class="alert alert-success font-jp">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <h1 class="heading-custom" data-en="User Info">ユーザー情報</h1>
    <div class="row">

      <div class="col-md-3">
        <%= render 'users/userinfo', user: @user %>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <div class="text-center btn-admin-custom">
            <%= link_to admin_requests_path, class: 'btn btn-block text-light font-jp' do %>
              管理者用ダッシュボードへ
            <% end %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="col-md-6">
        <section class="search mt-3">
          <div class="search-form-custom">
            <%= form_tag(search_path, method: "get", class: "form-inline") do %>
              <div class="input-group">
                <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "ゲームを検索" %>
                <div class="input-group-append">
                  <button class="btn btn-search-custom text-light" type="submit"><i class="fa fa-search"></i></button>
                </div>
              </div>
            <% end %>
          </div>
        </section>
        <section class="favorite section-back mt-3">
          <h3 class="font-al"><%= @user.name %>'s Game</h3>
          <p class="font-jp">お気に入り登録済みのゲーム</p>
          <% @user.favorite_games.each do |game| %>
            <ul class="favorite-list-custom">
              <li class="align-middle"><%= link_to game.title, game_path(game) %></li>
            </ul>
          <% end %>
        </section>
      </div>

      <div class="col-md-3 sidebar">
        <section class="latest-review section-back mt-3">
          <h3 class="latest-review-heading font-al">Latest Review</h3>
          <p class="font-jp">最新の課金レビュー</p>
          <div class="review-card">
            <% if @latest_review %>
              <h5 class="review-card-title pb-1"><%= link_to @latest_review.game.title, game_path(@game) %></h5>
              <h5 class="font-jp pb-2">
              <i class="fa-solid fa-wallet"></i> <%= @latest_review.package_name %>
              </h5>
              <p class="font-jp">
              <%= display_rating_icon(@latest_review.rating) %>
              <br>
              <%= @latest_review.comment %></p>
            <% else %>
              <p class="font-jp">このユーザーの課金レビューはありません。</p>
            <% end %>
          </div>
        </section>
      </div>
    </div>
  </div>
</main>