config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get "search" => "games#search"

  resources :users do
    resources :requests
  end

  resources :games do
    resources :reviews do
      member do
        post 'toggle_good'
      end
    end
    resources :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :requests do
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :favorited_by, through: :favorites, source: :user
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :status, inclusion: { in: %w(ios android), message: "はiOSまたはAndroidである必要があります" }
  validates :genre, presence: true
  validates :release_date, presence: true
  validates :developer, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def self.looks(search, word)
    if search == "perfect_match"
      @game = Game.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @game = Game.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @game = Game.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @game = Game.where("title LIKE?","%#{word}%")
    else
      @game = Game.all
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_admin, except: [:index, :show, :search]
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    if @game.save
      flash[:notice]= "ゲームを追加しました！"
      redirect_to game_path(@game)
    else
      @games = Game.all
      @user = User.find(current_user.id)
      render "index"
    end
  end

  def index
    @games = Game.all
    @user = User.find(current_user.id)
    @game = Game.new
  end

  def show
    @user = @game.user
    @review = Review.new
    @reviews = @game.reviews
  end

  def edit
    if @game.user == current_user
      render "edit"
    else
      redirect_to games_path
    end
  end

  def update
    @game.user_id = current_user.id
    if @game.update(game_params)
      flash[:notice]= "ゲーム情報を編集しました！！"
      redirect_to game_path(@game.id)
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  def search
    @query = params[:query]
    @games = Game.where("title LIKE ? OR genre LIKE ?", "%#{@query}%", "%#{@query}%")
    @user = User.find(current_user.id)
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :status, :genre, :release_date, :developer, :price, :payment_details)
  end

  def authenticate_admin
    redirect_to root_path, alert: 'アクセス権限がありません。' unless current_user&.admin?
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with model: @game, local:true do |f| %>
  <div class="form-group font-jp">
    <label for="game_title">ゲームタイトル</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="game_status" class="font-jp">対応機種</label>
    <div class="form-check mb-1">
      <%= f.check_box :status, { class: 'form-check-input' }, 'ios', nil %>
      <%= label_tag 'game_status_ios', 'iOS' %>
    </div>
    <div class="form-check">
      <%= f.check_box :status, { class: 'form-check-input' }, 'android', nil %>
      <%= label_tag 'game_status_android', 'Android' %>
    </div>
  </div>

  <div class="form-group font-jp">
    <label for="game_genre">ジャンル</label>
    <%= f.select :genre, [["シミュレーション","シミュレーション"],["パズル","パズル"],["RPG","RPG"],["アクション","アクション"],["アドベンチャー","アドベンチャー"],["パズル","パズル"],["育成","育成"],["ボード","ボード"],["スポーツ","スポーツ"],["レーシング","レーシング"],["音楽","音楽"],["その他","その他"]], {include_blank: "選択してください"}, class: 'form-control' %>
  </div>
  <div class="form-group font-jp">
    <label for="game_release">リリース日</label>
    <%= f.date_field :release_date, class: 'form-control'%>
  </div>
  <div class="form-group font-jp">
    <label for="game_developer">開発者</label>
    <%= f.text_field :developer, class: 'form-control' %>
  </div>
  <div class="form-group font-jp">
    <label for="game_price">価格</label>
    <%= f.number_field :price, class: 'form-control' %>
  </div>
  <div class="form-group font-jp">
    <label for="game_price">課金情報</label>
    <%= f.text_area :payment_details, class: 'form-control',placeholder: "課金情報を記入" %>
  </div>

  <div class="form-group font-jp">
    <button type="submit" class="btn btn-block btn-danger">ゲームを追加</button>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="container">
  <p id="notice"><%= flash[:notice] %></p>
  <div class="row">
    <div class="col-md-6 offset-col-md-6 mx-auto">
    <section class="edit-game-form section-back">
      <h3 class="font-al mb-3">Edit Game</h3>
        <%= form_with model: @game, local:true do |f| %>
        <div class="form-group">
          <label for="game_title">ゲームタイトル</label>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label for="game_status">対応機種</label>
          <div class="form-check">
            <%= f.check_box :status, { class: 'form-check-input' }, 'ios', nil %>
            <%= label_tag 'game_status_ios', 'iOS', class: 'form-check-label' %>
          </div>
          <div class="form-check">
            <%= f.check_box :status, { class: 'form-check-input' }, 'android', nil %>
            <%= label_tag 'game_status_android', 'Android', class: 'form-check-label' %>
          </div>
        </div>
        <div class="form-group">
          <label for="game_genre">ジャンル</label>
          <br>
          <%= f.select :genre, [["シミュレーション","シミュレーション"],["パズル","パズル"],["RPG","RPG"],["アクション","アクション"],["アドベンチャー","アドベンチャー"],["パズル","パズル"],["育成","育成"],["ボード","ボード"],["スポーツ","スポーツ"],["レーシング","レーシング"],["音楽","音楽"],["その他","その他"]],include_blank:"選択してください", class: 'form-control' %>
        </div>
        <div class="form-group">
          <label for="game_release">リリース日</label>
          <%= f.date_field :release_date %>
        </div>
        <div class="form-group">
          <label for="game_developer">開発者</label>
          <%= f.text_field :developer %>
        </div>
        <div class="form-group">
          <label for="game_price">価格</label>
          <%= f.number_field :price %>
        </div>
        <div class="form-group">
          <label for="game_price">課金情報</label>
          <%= f.text_area :payment_details, class: 'form-control',placeholder: "課金情報を記入" %>
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-block btn-success">ゲームを追加</button>
        </div>
        <% end %>
      </section>
    </div>
  </div>


  <%= link_to 'Show', games_path %>
|
  <%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<main>
  <div class="container px-5 px-sm-0 mt-3">
    <% if flash[:notice] %>
      <div class="alert alert-success font-jp">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <h1 class="heading-custom" data-en="All Games">ゲーム一覧</h1>
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/userinfo', user: @user %>
      </div>

      <div class="col-md-9">
        <section class="search mt-3">
          <div class="search-form-custom">
            <%= form_tag(search_path, method: "get", class: "form-inline") do %>
              <div class="input-group">
                <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "ゲームを検索" %>
                <div class="input-group-append">
                  <button class="btn btn-search-custom text-light" type="submit"><i class="fa fa-search"></i></button>
                </div>
              </div>
            <% end %>
          </div>
        </section>
        <section class="all-games section-back mt-3">
          <h3 class="font-al">Games</h3>
          <table class="table table-hover table-inverse text-center">
            <tbody>
              <% @games.each do |game| %>
              <tr>
                <td class="align-middle"><%= link_to game.title, game_path(game) %></td>
                <td class="align-middle"><%= game.genre %></td>
                <td class="align-middle"><%= link_to game.reviews.count, game_path(game) %> 件のレビュー</td>
                <td>
                  <% if current_user %>
                    <% if current_user.favorited?(game) %>
                      <%= link_to game_favorite_path(game, current_user.favorites.find_by(game: game)), method: :delete, class: "btn btn-favorite-d-custom" do %>
                      <i class="fa-solid fa-heart i-custom"></i>
                      <% end %>
                    <% else %>
                      <%= link_to game_favorites_path(game), method: :post, class: "btn btn-favorite-custom" do %>
                      <i class="fa-regular fa-heart i-custom"></i>
                      <% end %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </section>
      </div>
    </div>
  </div>
</main>

app/views/games/new.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
  <div class="col-md-6 offset-col-md-6 mx-auto">
  <section class="new-game-form section-back">
    <h3 class="font-al mb-3">New Game</h3>
      <%= render 'games/form' %>
    </div>

  <%= link_to 'Show', games_path %>
|
  <%= link_to 'Back', games_path %>
  </section>
</div>

app/views/games/search.html.erb
<div class="container">
  <section class="search">
    <div class="search-form-custom mt-3">
      <%= form_tag(search_path, method: "get", class: "form-inline") do %>
      <div class="input-group">
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "ゲームを検索" %>
        <div class="input-group-append">
          <button class="btn btn-search-custom text-light" type="submit"><i class="fa fa-search"></i></button>
        </div>
      </div>
      <% end %>
    </div>
  </section>
  <section class="search-result section-back mt-3">
  <h2 class="font-jp">検索結果</h2>
  <% if @games.any? %>
    <div class="card search-result">
      <% @games.each do |game| %>
      <ul>
        <li class="search-title">
          <%= link_to game.title, game %>
        </li>
        <li class="category">
          <%= game.genre %>
        </li>
      </ul>
      <% end %>
      <% else %>
        <p class="font-jp">該当するゲームは見つかりませんでした。</p>
        <h4 class="request-heading font-jp p-1">リクエスト送信ご協力のお願い <i class="fa-solid fa-paper-plane"></i> </h4>
        <p class="font-jp">サイト内のゲーム追加にご協力お願いします。</p>
          <%= link_to new_user_request_path(@user), class: 'btn btn-request-custom' do %>
            ⇒スマホゲームの追加リクエスト画面へ
          <% end %>
          <P class="font-jp mt-2">※リクエスト送信後、管理者に承認されれば一週間以内にゲーム一覧に追加されます。
          <br>※Home → リクエスト状況 からご確認ください。
          </P>
      <% end %>
    </div>

app/views/games/show.html.erb
<main>
  <div class="container px-5 px-sm-0 mt-3">
    <% if flash[:notice] %>
      <div class="alert alert-success font-jp">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger font-jp">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <h1 class="heading-custom" data-en="Review">レビュー</h1>
    <section class="game-date section-back mt-3">
      <h3 class="ml-2 font-jp"><%= link_to @game.title, game_path(@game) %></h3>
    <div class="row">
      <div class="col-md-6">
        <div>
          <% if current_user %>
            <% if current_user.favorites.exists?(game: @game) %>
              <%= link_to game_favorite_path(@game, @game), method: :delete, class: "btn btn-favorite-d-custom-show font-jp" do %>
                お気に入り登録済み <i class="fa-solid fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to game_favorites_path(@game), method: :post, class: "btn btn-favorite-custom-show font-jp" do %>
                お気に入り登録済み <i class="fa-regular fa-heart"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <table class="table game-date-table font-jp">
          <tbody>
            <tr>
              <th>ジャンル</th>
              <td><%= @game.genre %></td>
            </tr>
            <tr>
              <th>対応機種</th>
              <td><%= @game.status %></td>
            </tr>
            <tr>
              <th>価格</th>
              <td><%= @game.price %>円</td>
            </tr>
            <tr>
              <th>開発元</th>
              <td><%= @game.developer %></td>
            </tr>
            <tr>
              <th>リリース日</th>
              <td><%= @game.release_date %></td>
            </tr>
          </tbody>
        </table>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <div class="game-info-update font-jp">
              <%= link_to edit_game_path(@game), class: 'btn btn-outline-dark rounded-pill btn-block' do %>
                ゲーム情報を編集する <i class="fa-regular fa-pen-to-square"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-6 mt-3">
      <table class="table game-date-table font-jp">
        <tbody>
          <tr>
            <th>課金情報</th>
            <td><%= @game.payment_details %></td>
          </tr>
        </tbody>
      </table>
      </div>
    </div>
    </section>
    <section class="review-form section-back pr-3 pl-3 mt-3">
      <h3 class="font-al">New Review</h3>
      <p class="font-jp"><%= link_to @game.title, game_path(@game) %>の課金レビューを送信してください</p>
    <div class="row">
      <%= render 'reviews/form', model: [@game, @review] %>
    </div>
    </section>
    <section class="review-index section-back mt-3">
      <h3 class="font-al">Billing Review</h3>
      <p class="font-jp">アプリ内課金についてのレビュー一覧</p>
      <% if @reviews.any? %>
      <div class="review-cards">
        <% @reviews.each do |review| %>
          <div class="card m-3 p-3">
            <div class="card-title font-jp d-flex">
              <h4><%= review.package_name %></h4>
              <p class="ml-auto"><%= review.spent_amount %>円</p>
            </div>
            <h5><%= link_to display_rating_icon(review.rating), game_review_path(@game, review) %></h5>
            <p class="review-text mt-1 font-jp"><%= review.comment %></p>
            <p class="font-jp"><%= review.user.name %>_
            <% case review.seriousness_rating %>
              <% when 'max' %>
                ガチ勢
              <% when 'normal' %>
                こつこつ勢
              <% when 'low' %>
                のんびり勢
              <% else %>
                評価なし
            <% end %>
            _ <%= review.created_at&.strftime('%Y/%m/%d') %></p>
          </div>
        <% end %>
      </div>
      <% else %>
          <p class="font-jp">レビューはまだありません。</p>
      <% end %>
    </section>
  </div>
</main>