config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get "search" => "games#search"

  resources :users do
    resources :requests
  end

  resources :games do
    resources :reviews do
      member do
        post 'toggle_good'
      end
    end
    resources :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :requests do
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :status, presence: true
  validates :description, length: { maximum: 200 }

  after_initialize :set_initial_approval

  scope :pending_approval, -> { where(approval: '承認待ち') }
  scope :approved, -> { where(approval: '承認済み') }
  scope :rejected, -> { where(approval: '拒否済み') }

  def set_initial_approval
    self.approval ||= '承認待ち'
  end

  def approve!
    self.update_columns(approval: '承認済み')
  end

  def reject!
    self.update_columns(approval: '拒否済み')
  end
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  before_action :authenticate_admin
  before_action :set_request, only: [:approve, :reject, :edit, :update]

  def index
    @requests = Request.all
    @pending_approval_requests = Request.pending_approval
    @approved_requests = Request.approved
    @rejected_requests = Request.rejected
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:notice]="ゲームが追加されました！"
      redirect_to game_path(@game)
    else
      @requests = Request.all
      render "index"
    end
  end

  def approve
    if @request.approve!
      redirect_to admin_requests_path, notice: 'リクエストが承認されました。'
    else
      redirect_to admin_requests_path, alert: 'リクエストの承認に失敗しました。'
    end
  end

  def reject
    if @request.reject!
      redirect_to admin_requests_path, notice: 'リクエストが拒否されました。'
    else
      redirect_to admin_requests_path, alert: 'リクエストの拒否に失敗しました。'
    end
  end

  private

  def game_params
    params.require(:game).permit(:title, :status, :genre, :release_date, :developer, :price, :payment_details)
  end

  def set_request
    @request = Request.find(params[:id])
  end

  def authenticate_admin
    redirect_to root_path, alert: "アクセス権限がありません。" unless current_user&.admin?
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  def index
    @requests = @user.requests
  end

  def show
    @request = Request.find(params[:id])
  end

  def new
    @request = Request.new
  end

  def create
    @request = @user.requests.build(request_params)

    if @request.save
      flash[:notice]="リクエストが送信されました。"
      redirect_to user_requests_path
    else
      flash[:alert] = "リクエストの送信に失敗しました。"
      render "new"
    end
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    if @request.update(request_params)
      flash[:notice] = 'リクエストが更新されました。'
      redirect_to user_request_path(@request)
    else
      render 'edit'
    end
  end

  def destroy
    @request = Request.find(params[:id])
    if @request.destroy
      flash[:notice] = 'リクエストが削除されました。'
    else
      flash[:notice] = 'リクエストの削除に失敗しました。'
    end
    redirect_to user_requests_path
  end


  private

  def set_user
    @user = User.find(current_user.id)
  end

  def set_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:title, :description, :status)
  end


end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/admin/requests/_requests_list.html.erb
<table class="table table-hover table-inverse text-center font-jp">
  <tbody>
    <% requests.each do |request| %>
      <tr>
        <td><%= request.title %></td>
        <td><%= request.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td>
          <% if request.approval == '承認済み' %>
            承認済み
          <% elsif request.approval == '拒否済み' %>
            拒否済み
          <% else %>
            未承認
          <% end %>
        </td>
        <% if request.approval == '承認待ち' %>
        <td>
          <%= link_to '承認', approve_admin_request_path(request), method: :put , data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-sm " %>
          <%= link_to '拒否', reject_admin_request_path(request), method: :put, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        </td>
        <% elsif request.approval == '拒否済み' %>
        <td>
          <%= link_to '削除', admin_request_path(request), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <% end %>
      </tr>
      <tr>
        <%= request.description %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/requests/index.html.erb
<main>
  <div class="admin container px-5 px-sm-0 pt-3">
    <h1 class="heading-custom" data-en="Dash Board">管理者用ダッシュボード</h1>
    <div class="row">
      <div class="col-md-4 new-game-form">
        <section class="section-back mt-3">
        <h3 class="font-al">New Game</h3>
          <%= render 'games/form', model: @game %>
        </section>
      </div>

      <div class="col-md-8">
        <section class="section-back mt-3">
        <h3 class="font-al">All Requests</h3>
          <div class="tabs d-flex justify-content-between align-items-center">
            <ul class="nav nav-tabs">
              <li class="nav-item tab-label">
                <a class="nav-link tab-link active font-jp" data-toggle="tab" href="#pending_approval">承認待ち</a>
              </li>
              <li class="nav-item tab-label">
                <a class="nav-link tab-link font-jp" data-toggle="tab" href="#approved">承認済み</a>
              </li>
              <li class="nav-item tab-label">
                <a class="nav-link tab-link font-jp" data-toggle="tab" href="#rejected">拒否済み</a>
              </li>
            </ul>
          </div>
          <div class="tab-content">
            <div id="pending_approval" class="tab-pane fade show active">
              <%= render 'requests_list', requests: @pending_approval_requests %>
            </div>

            <div id="approved" class="tab-pane fade">
              <%= render 'requests_list', requests: @approved_requests %>
            </div>

            <div id="rejected" class="tab-pane fade">
              <%= render 'requests_list', requests: @rejected_requests %>
            </div>
          </div>
        </section>
      </div>

  </div>
  <div class="admin-overlay"></div>
</div>
</main>

app/views/admin/requests/show.html.erb
<h1>リクエスト詳細</h1>
<p><strong>タイトル:</strong> <%= @request.title %></p>
<p><strong>詳細:</strong> <%= @request.description %></p>