config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get "search" => "games#search"

  resources :users do
    resources :requests
  end

  resources :games do
    resources :reviews do
      member do
        post 'toggle_good'
      end
    end
    resources :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :requests do
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_game
  before_action :set_review, only: [:show, :edit, :update, :destroy, :toggle_good]

  def create
    @review = @game.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      redirect_to game_review_path(@game, @review), notice: "レビューが投稿されました。"
    else
      @game = Game.find(params[:game_id])
      @reviews = @game.reviews
      review = @game.reviews.find_by(id: params[:id])
      render "games/show"
    end
  end

  def show
    @user = User.find(current_user.id)
    @good_count = @review.helpful_count
  end

  def toggle_good
    existing_vote = @review.voted_for?(current_user)

    if existing_vote
      flash[:notice] = 'You have already voted for this review.'
    else
      ReviewVote.create(user: current_user, review: @review)
      @review.increment!(:helpful_count)
    end
    redirect_to game_review_path(@game, @review)
  end

  def edit
    if @review.user == current_user
      render "edit"
    else
      redirect_to game_path(@game)
    end
  end

  def update
    if @review.update(review_params)
      redirect_to game_review_path(@game, @review), notice: "レビューが更新されました。"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to game_path(@game), alert: "レビューが削除されました。"
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
  end

  def set_review
    @review = @game.reviews.find_by(id: params[:id])
    unless @review
      flash[:alert] = "レビューが見つかりませんでした。"
      redirect_to game_path(@game)
    end
  end

  def review_params
    params.require(:review).permit(:seriousness_rating, :package_name, :spent_amount, :rating, :comment)
  end
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/reviews/_form.html.erb
<div class="col-md-6">
    <%= form_with(model:[@game, @review], local: true) do |f| %>
      <% if @review.errors.any? %>
        <div id="error_explanation" class="alert alert-danger font-jp">
          <h5>以下の項目を修正してください。</h5>
          <ul>
            <% @review.errors.full_messages.each do |message| %>
              <li>・<%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <h5 class="font-jp">▼ このゲームに対する本気度</h5>
    <div class="form-radiobox radio-custom pb-3 d-flex text-center">
      <%= f.radio_button :seriousness_rating, :max, class: 'radiobutton' %>
        <%= f.label :seriousness_rating_max, "ガチ勢" %>
      <%= f.radio_button :seriousness_rating, :normal, class: 'radiobutton' %>
        <%= f.label :seriousness_rating_normal, "こつこつ勢" %>
      <%= f.radio_button :seriousness_rating, :low, class: 'radiobutton' %>
        <%= f.label :seriousness_rating_low, "のんびり勢" %>
    </div>
    <div class="form-group mt-3">
      <h5 class="font-jp">▼ ユーザーの課金情報</h5>
      <label class="font-jp">購入したアイテム・パッケージ名</label>
      <%= f.text_field :package_name, class: 'form-control' %>
      <label class="font-jp mt-3">課金・購入額</label>
      <%= f.number_field :spent_amount %> 円
    </div>
</div>
<div class="col-md-6">
    <h5 class="font-jp">▼ 課金した感想・おすすめ度</h5>
      <div class="form-radiobox">
        <%= f.radio_button :rating, "5", class: 'radiobutton' %>
          <label for="review_rating_5"><i class="fa-solid fa-face-laugh-squint"> Excellent</i></label>
        <%= f.radio_button :rating, "4", class: 'radiobutton' %>
          <label for="review_rating_4"><i class="fa-solid fa-face-smile"> Good</i></label>
        <%= f.radio_button :rating, "3", class: 'radiobutton' %>
          <label for="review_rating_3"><i class="fa-solid fa-face-meh"> Average</i></label>
        <%= f.radio_button :rating, "2", class: 'radiobutton' %>
          <label for="review_rating_2"><i class="fa-solid fa-face-frown-open"> Below Average</i></label>
        <%= f.radio_button :rating, "1", class: 'radiobutton' %>
          <label for="review_rating_1"><i class="fa-solid fa-face-sad-tear"> Poor</i></label>
      </div>
      <div class="form-group">
        <%= f.text_area :comment, class: 'form-control',placeholder: "感想、コメントを記入" %>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-block btn-success">レビューを送信</button>
      </div>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="container px-5 px-sm-0">
  <h1 class="heading-custom" data-en="Review Edit">レビューの編集</h1>
  <section class="game-date section-back mt-3">
    <h3 class="ml-2 font-jp"><%= link_to @game.title, game_path(@game) %></h3>
    <div class="row">
      <div class="col-md-6">
        <div>
          <% if current_user %>
            <% if current_user.favorites.exists?(game: @game) %>
              <%= link_to game_favorite_path(@game), method: :delete, class: "btn btn-favorite-d-custom-show" do %>
                お気に入り登録済み <i class="fa-solid fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to game_favorites_path(@game), method: :post, class: "btn btn-favorite-custom-show" do %>
                お気に入り登録済み <i class="fa-regular fa-heart"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <table class="table game-date-table">
          <tbody>
            <tr>
              <th>ジャンル</th>
              <td><%= @game.genre %></td>
            </tr>
            <tr>
              <th>対応機種</th>
              <td><%= @game.status %></td>
            </tr>
            <tr>
              <th>価格</th>
              <td><%= @game.price %>円</td>
            </tr>
            <tr>
              <th>開発元</th>
              <td><%= @game.developer %></td>
            </tr>
            <tr>
              <th>リリース日</th>
              <td><%= @game.release_date %></td>
            </tr>
          </tbody>
        </table>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <div class="game-info-update">
              <%= link_to edit_game_path(@game), class: 'btn btn-outline-dark rounded-pill btn-block' do %>
                ゲーム情報を編集する <i class="fa-regular fa-pen-to-square"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
    </div>
    <div class="col-md-6 p-3 mt-3">
      <h4 class="font-jp">課金情報</h4>
      <div><%= @game.payment_details %></div>
    </div>
  </div>
  </section>
  <section class="review-form section-back pr-3 pl-3 mt-3">
    <h3 class="font-al">Update Review</h3>
    <p class="font-jp"><%= link_to @game.title, game_path(@game) %>のレビューを編集してください</p>
    <div class="row">
      <%= render 'reviews/form', model: [@game, @review] %>
    </div>
  </section>
</div>

app/views/reviews/show.html.erb
<main>
  <div class="container px-5 px-sm-0 mt-3">
    <% if flash[:notice] %>
      <div class="alert alert-success font-jp">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <h1 class="heading-custom" data-en="Review">レビュー</h1>
    <div class="row">
      <div class="col-md-6">
        <section class="search mt-3">
          <div class="search-form-custom">
            <%= form_tag(search_path, method: "get", class: "form-inline") do %>
            <div class="input-group">
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "ゲームを検索" %>
              <div class="input-group-append">
                <button class="btn btn-search-custom text-light" type="submit"><i class="fa fa-search"></i></button>
              </div>
            </div>
            <% end %>
          </div>
        </section>
        <section class="game-date section-back mt-3">
          <h3 class="ml-2 font-jp"><%= link_to @game.title, game_path(@game) %></h3>
          <div>
            <% if current_user %>
              <% if current_user.favorites.exists?(game: @game) %>
                <%= link_to game_favorite_path(@game), method: :delete, class: "btn btn-favorite-d-custom-show" do %>
                  お気に入り登録済み <i class="fa-solid fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to game_favorites_path(@game), method: :post, class: "btn btn-favorite-custom-show" do %>
                  お気に入り登録済み <i class="fa-regular fa-heart"></i>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <table class="table game-date-table">
            <tbody>
              <tr>
                <th>ジャンル</th>
                <td><%= @game.genre %></td>
              </tr>
              <tr>
                <th>対応機種</th>
                <td><%= @game.status %></td>
              </tr>
              <tr>
                <th>価格</th>
                <td><%= @game.price %>円</td>
              </tr>
              <tr>
                <th>開発元</th>
                <td><%= @game.developer %></td>
              </tr>
              <tr>
                <th>リリース日</th>
                <td><%= @game.release_date %></td>
              </tr>
            </tbody>
          </table>
        </section>
      </div>

      <div class="col-md-6">
        <section class="review-show section-back mt-3">
          <h3 class="font-al">
            <%= link_to game_path(@game), class:'btn btn-outline-dark rounded-pill btn-sm' do %>
            <i class="fa-solid fa-arrow-left"></i>
            <% end %>
            Review
          </h3>
          <div class="card m-3">
            <div class="card-body">
              <div class="card-title font-jp d-flex">
                <h4><%= @review.package_name %></h4>
                <p class="ml-auto">課金額：<%= @review.spent_amount %>円</p>
              </div>
              <h5 class="card-text"><%= display_rating_icon(@review.rating) %></h5>
              <p class="card-text font-jp"><%= @review.comment %></p>
              <% if @review.voted_for?(current_user) %>
                <%= link_to toggle_good_game_review_path(@game, @review), method: :post do %>
                  <i class="fa-solid fa-thumbs-up"></i> <%= @review.helpful_count %>
                <% end %>
              <% else %>
                <%= link_to toggle_good_game_review_path(@game, @review), method: :post do %>
                  <i class="fa-regular fa-thumbs-up"></i> <%= @review.helpful_count %>
                <% end %>
              <% end %>
              <p class="font-jp pt-2"><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "user.png", size: '40x40' %>
                <%= link_to @review.user.name, user_path(@review.user) %> _
                <% case @review.seriousness_rating %>
                  <% when 'max' %>
                    ガチ勢
                  <% when 'normal' %>
                    こつこつ勢
                  <% when 'low' %>
                    のんびり勢
                  <% else %>
                    評価なし
                <% end %>
                 _<%= @review.created_at.strftime('%Y/%m/%d') %></p>
                <% if current_user && current_user == @review.user %>
                  <div class="review-update mx-auto">
                    <%= link_to edit_game_review_path(@game, @review) do %>
                      編集 <i class="fa-regular fa-pen-to-square"></i>
                    <% end %>
                    |
                    <%= link_to game_review_path(@game, @review), method: :delete, data: { confirm: "本当に削除しますか？" } do %>
                      削除 <i class="fa-solid fa-trash"></i>
                    <% end %>
                  </div>
                <% end %>
            </div>
        </section>
      </div>
    </div>
  </div>
</main>